export const companies = [
  { id: '1', name: 'Company A', address: 'Address A', employeesCount: 10 },
  { id: '2', name: 'Company B', address: 'Address B', employeesCount: 10 },
  { id: '3', name: 'Company C', address: 'Address C', employeesCount: 9 },
  { id: '4', name: 'Company D', address: 'Address D', employeesCount: 0 },
  { id: '5', name: 'Company E', address: 'Address E', employeesCount: 0 },
  { id: '6', name: 'Company F', address: 'Address F', employeesCount: 0 },
  { id: '7', name: 'Company G', address: 'Address G', employeesCount: 0 },
  { id: '8', name: 'Company H', address: 'Address H', employeesCount: 0 },
  { id: '9', name: 'Company I', address: 'Address I', employeesCount: 0 },
  { id: '10', name: 'Company J', address: 'Address J', employeesCount: 0 },
  { id: '11', name: 'Company K', address: 'Address K', employeesCount: 0 },
  { id: '12', name: 'Company L', address: 'Address L', employeesCount: 0 },
  { id: '13', name: 'Company M', address: 'Address M', employeesCount: 0 },
  { id: '14', name: 'Company N', address: 'Address N', employeesCount: 0 },
  { id: '15', name: 'Company O', address: 'Address O', employeesCount: 0 },
  { id: '16', name: 'Company P', address: 'Address P', employeesCount: 0 },
  { id: '17', name: 'Company Q', address: 'Address Q', employeesCount: 0 },
  { id: '18', name: 'Company R', address: 'Address R', employeesCount: 3 },
  { id: '19', name: 'Company S', address: 'Address S', employeesCount: 0 },
  { id: '20', name: 'Company T', address: 'Address T', employeesCount: 2 },
  { id: '21', name: 'Company U', address: 'Address U', employeesCount: 0 },
  { id: '22', name: 'Company V', address: 'Address V', employeesCount: 0 },
  { id: '23', name: 'Company W', address: 'Address W', employeesCount: 0 },
  { id: '24', name: 'Company X', address: 'Address X', employeesCount: 0 },
  { id: '25', name: 'Company Y', address: 'Address Y', employeesCount: 0 },
  { id: '26', name: 'Company Z', address: 'Address Z', employeesCount: 0 },
  // { id: '27', name: 'Company AA', address: 'Address AA', employeesCount: 0 },
  // { id: '28', name: 'Company AB', address: 'Address AB', employeesCount: 0 },
  // { id: '29', name: 'Company AC', address: 'Address AC', employeesCount: 0 },
  // { id: '30', name: 'Company AD', address: 'Address AD', employeesCount: 0 },
  // { id: '31', name: 'Company AE', address: 'Address AE', employeesCount: 0 },
  // { id: '32', name: 'Company AF', address: 'Address AF', employeesCount: 0 },
  // { id: '33', name: 'Company AG', address: 'Address AG', employeesCount: 0 },
  // { id: '34', name: 'Company AH', address: 'Address AH', employeesCount: 0 },
  // { id: '35', name: 'Company AI', address: 'Address AI', employeesCount: 0 },
  // { id: '36', name: 'Company AJ', address: 'Address AJ', employeesCount: 0 },
  // { id: '37', name: 'Company AK', address: 'Address AK', employeesCount: 0 },
  // { id: '38', name: 'Company AL', address: 'Address AL', employeesCount: 0 },
  // { id: '39', name: 'Company AM', address: 'Address AM', employeesCount: 0 },
  // { id: '40', name: 'Company AN', address: 'Address AN', employeesCount: 0 },
  // { id: '41', name: 'Company AO', address: 'Address AO', employeesCount: 0 },
  // { id: '42', name: 'Company AP', address: 'Address AP', employeesCount: 0 },
  // { id: '43', name: 'Company AQ', address: 'Address AQ', employeesCount: 0 },
  // { id: '44', name: 'Company AR', address: 'Address AR', employeesCount: 0 },
  // { id: '45', name: 'Company AS', address: 'Address AS', employeesCount: 0 },
  // { id: '46', name: 'Company AT', address: 'Address AT', employeesCount: 0 },
  // { id: '47', name: 'Company AU', address: 'Address AU', employeesCount: 0 },
  // { id: '48', name: 'Company AV', address: 'Address AV', employeesCount: 0 },
  // { id: '49', name: 'Company AW', address: 'Address AW', employeesCount: 0 },
  // { id: '50', name: 'Company AX', address: 'Address AX', employeesCount: 0 },
  // { id: '51', name: 'Company AY', address: 'Address AY', employeesCount: 0 },
  // { id: '52', name: 'Company AZ', address: 'Address AZ', employeesCount: 0 },
  // { id: '53', name: 'Company BA', address: 'Address BA', employeesCount: 0 },
  // { id: '54', name: 'Company BB', address: 'Address BB', employeesCount: 0 },
  // { id: '55', name: 'Company BC', address: 'Address BC', employeesCount: 0 },
  // { id: '56', name: 'Company BD', address: 'Address BD', employeesCount: 0 },
  // { id: '57', name: 'Company BE', address: 'Address BE', employeesCount: 0 },
  // { id: '58', name: 'Company BF', address: 'Address BF', employeesCount: 0 },
  // { id: '59', name: 'Company BG', address: 'Address BG', employeesCount: 0 },
  // { id: '60', name: 'Company BH', address: 'Address BH', employeesCount: 0 },
  // { id: '61', name: 'Company BI', address: 'Address BI', employeesCount: 0 },
  // { id: '62', name: 'Company BJ', address: 'Address BJ', employeesCount: 0 },
  // { id: '63', name: 'Company BK', address: 'Address BK', employeesCount: 0 },
  // { id: '64', name: 'Company BL', address: 'Address BL', employeesCount: 0 },
  // { id: '65', name: 'Company BM', address: 'Address BM', employeesCount: 0 },
  // { id: '66', name: 'Company BN', address: 'Address BN', employeesCount: 0 },
  // { id: '67', name: 'Company BO', address: 'Address BO', employeesCount: 0 },
  // { id: '68', name: 'Company BP', address: 'Address BP', employeesCount: 0 },
  // { id: '69', name: 'Company BQ', address: 'Address BQ', employeesCount: 0 },
  // { id: '70', name: 'Company BR', address: 'Address BR', employeesCount: 0 },
  // { id: '71', name: 'Company BS', address: 'Address BS', employeesCount: 0 },
  // { id: '72', name: 'Company BT', address: 'Address BT', employeesCount: 0 },
  // { id: '73', name: 'Company BU', address: 'Address BU', employeesCount: 0 },
  // { id: '74', name: 'Company BV', address: 'Address BV', employeesCount: 0 },
  // { id: '75', name: 'Company BW', address: 'Address BW', employeesCount: 0 },
  // { id: '76', name: 'Company BX', address: 'Address BX', employeesCount: 0 },
  // { id: '77', name: 'Company BY', address: 'Address BY', employeesCount: 0 },
  // { id: '78', name: 'Company BZ', address: 'Address BZ', employeesCount: 0 },
  // { id: '79', name: 'Company CA', address: 'Address CA', employeesCount: 0 },
  // { id: '80', name: 'Company CB', address: 'Address CB', employeesCount: 0 },
];
